name: Deploy
on:
  push:
    branches: [ main ]  # Asegúrate de que se active en la rama correcta.

jobs:
  build:
    runs-on: ubuntu-latest  # Simplifica: no necesitas múltiples OS/Node para un deploy.

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Usa una versión fija (evita matrices innecesarias).

      - name: Instalar dependencias
        run: |
          npm ci
          npm install -g jest

      - name: Run tests
        run: npm run test

      - name: Build page 
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public  # Asegúrate de que coincida con la carpeta de tu build.

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write  # Permisos necesarios para desplegar.
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
