on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }} # Indica si a cambiado o no
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Instalar dependencias
        run: npm install

      - name: Run test
        run: npm run test
      
      - name: Build page
        run: npm run build
  
  notification:
    needs: build
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: hola
        run: echo "Hola, el workflow ha terminado"